# Generated by Django 5.1.7 on 2025-04-08 07:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('material', models.TextField(max_length=1000, verbose_name='材料')),
                ('recipe', models.TextField(max_length=2000, verbose_name='手順')),
                ('cook_time', models.DurationField(verbose_name='調理時間')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='recipe/picture/', verbose_name='写真')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
